// Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ · 微信 zhuatech / zhuatech2
/** 有限排样和身份表单；毫米精度及数量由服务端再次验证。官网 https://www.zhuatech.cn/；微信 zhuatech / zhuatech2。 */
export const fields = {
  jobs: [
    ["reference", "方案编号", "Reference"],
    ["name", "方案名称", "Name"],
    ["departmentId", "负责部门", "Department", "id", "departments"],
    ["category", "材料类型", "Material type", "select", "categories"],
    ["material", "材料规格／厚度说明", "Material / thickness"],
    ["width", "板材宽（mm）", "Sheet width (mm)", "decimal"],
    ["height", "板材高（mm）", "Sheet height (mm)", "decimal"],
    ["margin", "四边留边（mm）", "Edge margin (mm)", "decimal"],
    ["kerf", "切缝宽（mm）", "Kerf (mm)", "decimal"],
    ["maxSheets", "最多板数（1—30）", "Maximum sheets (1–30)", "integer"],
    ["reviewerId", "独立复核人", "Independent reviewer", "id", "reviewers"],
    ["operatorId", "实物登记人", "Results operator", "id", "operators"],
    [
      "instructions",
      "加工约束／登记说明",
      "Constraints / instructions",
      "textarea",
    ],
  ],
  parts: [
    ["code", "零件编号", "Part code"],
    ["name", "零件名称", "Part name"],
    ["width", "零件宽（mm）", "Part width (mm)", "decimal"],
    ["height", "零件高（mm）", "Part height (mm)", "decimal"],
    ["quantity", "需求数量（整数）", "Quantity (integer)", "integer"],
    ["rotation", "允许旋转90°", "Allow 90° rotation", "boolean"],
  ],
  results: [
    ["good", "合格数量", "Good count", "integer"],
    ["scrap", "报废数量", "Scrap count", "integer"],
    ["notCut", "未切数量", "Not cut count", "integer"],
    ["note", "实际情况／异常说明", "Actual facts / exceptions", "textarea"],
  ],
  command: [["note", "操作事实／原因", "Reason / facts", "textarea"]],
  users: [
    ["username", "登录名", "Username"],
    ["displayName", "姓名", "Name"],
    [
      "password",
      "新密码（编辑时留空保留）",
      "New password (optional when editing)",
      "password",
    ],
    ["roleId", "角色", "Role", "id", "roles"],
    ["departmentId", "部门", "Department", "id", "departments"],
    ["enabled", "启用", "Enabled", "boolean"],
  ],
  roles: [
    ["name", "角色名称", "Role name"],
    ["scope", "数据范围", "Data scope", "select", "scope"],
    ["permissions", "接口权限", "API permissions", "permissions"],
  ],
  departments: [["name", "部门名称", "Department name"]],
  menus: [
    ["name", "中文名称", "Chinese name"],
    ["nameEn", "英文名称", "English name"],
    [
      "permissionCode",
      "所需权限",
      "Required permission",
      "select",
      "permissions",
    ],
    ["position", "排序", "Order", "integer"],
    ["enabled", "启用", "Enabled", "boolean"],
  ],
  permissions: [["name", "权限说明", "Permission description"]],
  dictionaries: [
    ["type", "字典类型", "Dictionary type"],
    ["code", "编码", "Code"],
    ["name", "中文名称", "Chinese name"],
    ["nameEn", "英文名称", "English name"],
  ],
  settings: [["value", "参数值", "Value"]],
};
